/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/myCharacter.glb --transform 
Files: public/myCharacter.glb [120.47KB] > /Users/gavinreekie/Desktop/district10/my-r3f-game2/myCharacter-transformed.glb [66.52KB] (45%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/myCharacter-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Object_4" scale={0.019}>
          <primitive object={nodes._rootJoint} />
        </group>
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Character_Male_GreenJacket} skeleton={nodes.Object_7.skeleton} scale={0.019} />
      </group>
    </group>
  )
}

useGLTF.preload('/myCharacter-transformed.glb')
