/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/avatar.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/avatar.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
          <group name="SM_security_alarm_1" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="Empty" position={[7.991, -0.082, -38.245]} scale={[17.662, 15.745, 16.806]} />
        <group name="Empty003" position={[7.991, -0.082, -38.245]} scale={[17.662, 15.745, 16.806]} />
        <group name="LINE" position={[44.031, -0.082, 1.392]} scale={[1.051, 0.937, 1]} />

        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Character_Male_GreenJacket} />
        <mesh name="Letter_02_-_Default_0" geometry={nodes['Letter_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-165.951, -896.45, -2092.177]} rotation={[-0.661, -0.078, 2.014]} scale={88.86} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[52.34, -0.082, 0]} scale={[1.051, 0.937, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/avatar.glb')
