/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 officeScene14.glb --transform 
Files: officeScene14.glb [2.26MB] > /Users/gavinreekie/Desktop/district10/my-r3f-game2/public/officeScene14-transformed.glb [973KB] (57%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/officeScene14-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode002" position={[-6.807, -1.865, 24.923]} rotation={[2.98, 0.636, -Math.PI]} scale={0.011}>
          <group name="Object_4003">
            <group name="_rootJoint">
              <group name="mixamorigHips_00" position={[0, 1.018, -0.013]}>
                <group name="mixamorigSpine_01" position={[0, 9.393, -0.732]} rotation={[-0.078, 0, 0]}>
                  <group name="mixamorigSpine1_02" position={[0, 10.991, 0]}>
                    <group name="mixamorigSpine2_03" position={[0, 12.561, 0]}>
                      <group name="mixamorigNeck_04" position={[0, 14.131, 0]} rotation={[0.078, 0, 0]}>
                        <group name="mixamorigHead_05" position={[-0.724, 10.752, 12.816]} />
                      </group>
                      <group name="mixamorigLeftShoulder_07" position={[4.833, 11.991, -0.198]} rotation={[1.553, -0.415, -1.615]}>
                        <group name="mixamorigLeftArm_08" position={[0, 10.576, 0]} rotation={[-0.386, -0.009, 0.021]}>
                          <group name="mixamorigLeftForeArm_09" position={[0, 27.652, 0]} rotation={[0.189, 0.072, 0.429]}>
                            <group name="mixamorigLeftHand_010" position={[0, 6.688, 0]} rotation={[-0.27, 0.038, -0.33]}>
                              <group name="mixamorigLeftHand_010_end" position={[0, 18.333, 0]} />
                            </group>
                          </group>
                        </group>
                      </group>
                      <group name="mixamorigRightShoulder_011" position={[-4.832, 11.986, -0.136]} rotation={[1.558, 0.416, 1.602]}>
                        <group name="mixamorigRightArm_012" position={[0, 10.576, 0]} rotation={[-0.388, -0.001, 0.002]}>
                          <group name="mixamorigRightForeArm_013" position={[0, 27.659, 0]} rotation={[-0.072, 0.009, -0.119]}>
                            <group name="mixamorigRightHand_014" position={[0.239, 27.467, -0.123]} rotation={[0.221, 0, -0.004]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="mixamorigLeftUpLeg_015" position={[8.187, -5.223, -0.077]} rotation={[0.017, 0, -3.132]}>
                  <group name="mixamorigLeftLeg_016" position={[0, 44.66, 0]} rotation={[0.006, 0, -0.005]}>
                    <group name="mixamorigLeftFoot_017" position={[0, 42.272, 0]} rotation={[0.916, 0.013, -0.016]}>
                      <group name="mixamorigLeftToeBase_018" position={[0.107, 19.573, 3.415]} rotation={[0.661, 0.025, -0.019]}>
                        <group name="mixamorigLeftToe_End_019" position={[9.041, -14.521, -0.105]} rotation={[-1.566, -0.04, 3.112]}>
                          <group name="mixamorigLeftToe_End_019_end" position={[0, 12.723, 0]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="mixamorigRightUpLeg_020" position={[-8.188, -5.223, -0.08]} rotation={[0.014, 0, 3.132]}>
                  <group name="mixamorigRightLeg_021" position={[0, 44.657, 0]} rotation={[-0.001, 0, 0.005]}>
                    <group name="mixamorigRightFoot_022" position={[0, 42.274, 0]} rotation={[0.92, -0.012, 0.016]}>
                      <group name="mixamorigRightToeBase_023" position={[-0.14, 20.964, 4.498]} rotation={[-2.487, -0.288, -0.02]}>
                        <group name="mixamorigRightToe_End_024" position={[-8.57, 16.288, 2.877]} rotation={[1.588, 0.036, 2.859]}>
                          <group name="mixamorigRightToe_End_024_end" position={[0, 12.723, 0]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh name="EntranceSideEast001" geometry={nodes.EntranceSideEast001.geometry} material={nodes.EntranceSideEast001.material} position={[-6.467, -1.934, -4.222]} scale={[1.069, 0.953, 1.017]} />
        <mesh name="port1Sides018" geometry={nodes.port1Sides018.geometry} material={materials['Material.019']} position={[-0.587, -0.219, -4.716]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides018" geometry={nodes.port0Sides018.geometry} material={materials['Material.020']} position={[-0.587, -0.219, -7.323]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End003" geometry={nodes.port0End003.geometry} material={materials['whiteCabin.001']} position={[-0.587, -0.219, -7.323]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides020" geometry={nodes.port1Sides020.geometry} material={materials['Material.021']} position={[-0.587, -0.219, -15.132]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides021" geometry={nodes.port1Sides021.geometry} material={materials['Material.022']} position={[-0.587, 3.207, -15.132]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides023" geometry={nodes.port1Sides023.geometry} material={materials['Sides.002']} position={[-0.587, 3.207, -4.746]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides026" geometry={nodes.port1Sides026.geometry} material={materials['Material.023']} position={[-0.587, 6.634, -15.132]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides032" geometry={nodes.port1Sides032.geometry} material={materials['Material.025']} position={[-15.202, 3.207, -15.132]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides033" geometry={nodes.port1Sides033.geometry} material={materials['Material.026']} position={[-15.202, -0.219, -15.132]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End001" geometry={nodes.port1End001.geometry} material={materials['greyCabinPlain.001']} position={[-0.587, -0.219, -15.132]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides019" geometry={nodes.port0Sides019.geometry} material={materials['cabinTopRight.001']} position={[-0.587, -0.219, -12.489]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides022" geometry={nodes.port1Sides022.geometry} material={materials['Sides.001']} position={[-0.587, 3.207, -9.924]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End005" geometry={nodes.port1End005.geometry} material={materials['CABINLSHAPEYELLOW.001']} position={[-0.587, 3.207, -15.132]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides027" geometry={nodes.port1Sides027.geometry} material={materials['Material.024']} position={[-20.127, 6.634, -13.829]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides034" geometry={nodes.port1Sides034.geometry} material={materials['cabinBottomRight.001']} position={[-15.202, -0.219, -9.908]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End022" geometry={nodes.port1End022.geometry} material={materials.glassLong} position={[-15.199, -0.219, -4.746]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="portPanelRight012" geometry={nodes.portPanelRight012.geometry} material={materials['yellowCabinDoor.001']} position={[-20.897, 6.633, -15.903]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.017]} />
        <mesh name="portPanelRight014" geometry={nodes.portPanelRight014.geometry} material={materials['whitePortacabinDoor.001']} position={[-20.897, 6.633, -8.091]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.017]} />
        <mesh name="roofFrontBeamLeft001" geometry={nodes.roofFrontBeamLeft001.geometry} material={materials['leftRoof.001']} position={[-15.251, 8.497, -0.871]} scale={[5.031, 0.15, 0.12]} />
        <mesh name="EntranceSignLarge001" geometry={nodes.EntranceSignLarge001.geometry} material={materials['Material.027']} position={[-8.843, 0.098, -0.769]} rotation={[Math.PI, 0, Math.PI]} scale={[0.323, 0.417, 0.01]} />
        <mesh name="circleLightLeft003" geometry={nodes.circleLightLeft003.geometry} material={materials['circleLightBlack.002']} position={[-11.229, 1.34, -0.81]} rotation={[Math.PI / 2, 0, 0]} scale={0.171} />
        <mesh name="alarmTop001" geometry={nodes.alarmTop001.geometry} material={materials['alarmTexture.001']} position={[-8.85, 1.727, -0.722]} scale={0.017} />
        <mesh name="roofLeft001" geometry={nodes.roofLeft001.geometry} material={materials.leftRoof} position={[-14.774, 8.454, -8.757]} scale={[5.507, 0.095, 7.718]} />
        <mesh name="roofRight002" geometry={nodes.roofRight002.geometry} material={materials['Material.028']} position={[-1.004, 8.454, -8.757]} scale={[5.512, 0.095, 7.718]} />
        <mesh name="roofRight003" geometry={nodes.roofRight003.geometry} material={materials['Material.029']} position={[-7.889, 8.454, -8.435]} scale={[1.357, 0.095, 5.384]} />
        <mesh name="WINDOW017" geometry={nodes.WINDOW017.geometry} material={materials.glassLong} position={[-20.127, 6.749, -5.994]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.009, 0.013]} />
        <mesh name="ground001" geometry={nodes.ground001.geometry} material={materials['Material.031']} position={[-7.827, -2.949, 51.441]} scale={[18.85, 1.017, 52.187]} />
        <mesh name="Car_Material002_0001" geometry={nodes.Car_Material002_0001.geometry} material={materials['Material.033']} position={[-3.471, -1.305, 5.335]} rotation={[-Math.PI / 2, 0, 1.576]} scale={1.259} />
        <mesh name="Tire1_tire1002_0001" geometry={nodes.Tire1_tire1002_0001.geometry} material={materials['tyre.001']} position={[-2.513, -1.417, 2.944]} rotation={[-Math.PI / 2, 0, 1.576]} scale={1.259} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['LicensePlate.001']} position={[-7.916, 3.104, -4.081]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-2.392, -5.248, -0.992]} />
        <mesh name="topTowerRoof" geometry={nodes.topTowerRoof.geometry} material={materials['Material.036']} position={[-8.124, 11.563, -1.922]} scale={[1.402, 1.278, 1.139]} />
        <group name="glassBottomSide" position={[-6.972, -0.825, -0.785]} rotation={[0, 0, -Math.PI]} scale={[-0.149, -1.055, -0.004]}>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.frameYellow} />
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Scene_-_Root']} />
        </group>
        <group name="frontContainers" position={[-0.507, -0.325, -2.068]} rotation={[0, 1.571, 0]} scale={0.679}>
          <mesh name="Cube_Front_0" geometry={nodes.Cube_Front_0.geometry} material={materials['Material.002']} />
          <mesh name="Cube_Front_0_1" geometry={nodes.Cube_Front_0_1.geometry} material={materials['Material.018']} />
        </group>
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.Material} position={[-7.881, -2.001, -2.819]} scale={[1.31, 1.075, 1.076]} />
        <mesh name="Letter_02_-_Default_0" geometry={nodes['Letter_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-6.807, -1.88, 22.821]} rotation={[-2.917, -0.95, -2.795]} scale={0} />
        <mesh name="Object_4004" geometry={nodes.Object_4004.geometry} material={materials['hedge.003']} position={[4.685, -1.929, -2.63]} scale={[1.017, 0.775, 1.541]} />
        <mesh name="Object_5003" geometry={nodes.Object_5003.geometry} material={materials['TexturesCom_Branches0026_1_S.003']} position={[4.685, -1.929, -2.63]} scale={[1.017, 0.775, 1.541]} />
        <mesh name="Object_4005" geometry={nodes.Object_4005.geometry} material={materials['hedge.004']} position={[4.685, -1.929, -5.203]} scale={[1.017, 0.775, 1.541]} />
      </group>
    </group>
  )
}

useGLTF.preload('/officeScene14-transformed.glb')
