/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/scene.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty001" position={[51.371, 6.999, -0.451]} rotation={[Math.PI / 2, 0, 0]} scale={4.985} />
        <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
          <group name="SM_security_alarm_1" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="root">
          <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <group name="security_alarm_0" />
          </group>
        </group>
        <group name="265f242c0def4d35bc5c349c33a09ffdfbx" rotation={[Math.PI / 2, 0, 0]}>
          <group name="RootNode">
            <group name="ExitSign" position={[0, 2.324, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <group name="SindleDoor" rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          </group>
        </group>
        <group name="Sketchfab_model" position={[0, 0, 9.677]} rotation={[-Math.PI / 2, 0, -0.736]} scale={0.909}>
          <group name="b38e473ff2484b0b9968d3cd78b5ee6ffbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode001">
              <group name="Car" position={[0, 50.463, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <group name="LicensePlate">
                  <mesh name="LicensePlate_LicensePlate_0" geometry={nodes.LicensePlate_LicensePlate_0.geometry} material={materials.LicensePlate} position={[-3.479, 3.556, 0.059]} rotation={[0, 0, 2.308]} scale={1.318} />
                </group>
                <group name="Tire1" position={[1.894, -0.771, -0.089]}>
                  <mesh name="Tire1_tire1002_0" geometry={nodes.Tire1_tire1002_0.geometry} material={materials['tire1.002']} position={[-6.299, 6.858, 0.031]} rotation={[0, 0, 2.308]} scale={1.318} />
                </group>
                <group name="Tire2" position={[-1.479, -0.771, -0.089]}>
                  <mesh name="Tire2_tire1002_0" geometry={nodes.Tire2_tire1002_0.geometry} material={materials['tire1.002']} position={[0.062, 3.569, 0.031]} rotation={[0, 0, 2.308]} scale={1.318} />
                </group>
                <group name="Tire3" position={[-1.479, 0.606, -0.089]} rotation={[0, 0, Math.PI]}>
                  <mesh name="Tire3_tire1002_0" geometry={nodes.Tire3_tire1002_0.geometry} material={materials['tire1.002']} position={[1.281, -0.971, 0.031]} rotation={[0, 0, 2.308]} scale={1.318} />
                </group>
                <group name="Tire4" position={[1.894, 0.606, -0.089]} rotation={[0, 0, Math.PI]}>
                  <mesh name="Tire4_tire1002_0" geometry={nodes.Tire4_tire1002_0.geometry} material={materials['tire1.002']} position={[7.642, -4.26, 0.031]} rotation={[0, 0, 2.308]} scale={1.318} />
                </group>
                <mesh name="Car_Material002_0" geometry={nodes.Car_Material002_0.geometry} material={materials['Material.018']} position={[-3.479, 3.556, 0.059]} rotation={[0, 0, 2.308]} scale={1.318} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" rotation={[-Math.PI / 2, 0, 0]} scale={0.19}>
          <group name="root001">
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="marker_blue_0" scale={[35.345, 17.142, 35.345]} />
              <group name="marker_green_2" position={[-88, 0, 0]} scale={[35.345, 17.142, 35.345]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.green} position={[1.349, 0.104, 0.081]} scale={0.117} />
              </group>
              <group name="marker_red_1" position={[88, 0, 0]} scale={[35.345, 17.142, 35.345]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model002" position={[4.949, -0.078, -2.627]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.515, 0.762]}>
          <group name="root002">
            <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
              <group name="HEDGE_30" position={[-0.003, 0, 0.007]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.hedge} position={[-0.407, 0, 0]} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.TexturesCom_Branches0026_1_S} position={[-0.407, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model003" position={[4.949, -0.078, -5.157]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.515, 0.762]}>
          <group name="root003">
            <group name="GLTF_SceneRootNode003" rotation={[Math.PI / 2, 0, 0]}>
              <group name="HEDGE_30001" position={[-0.003, 0, 0.007]}>
                <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials['hedge.001']} position={[-0.407, 0, 0]} />
                <mesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials['TexturesCom_Branches0026_1_S.001']} position={[-0.407, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[4.949, -0.078, -7.686]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1.515, 0.762]}>
          <group name="root004">
            <group name="GLTF_SceneRootNode004" rotation={[Math.PI / 2, 0, 0]}>
              <group name="HEDGE_30002" position={[-0.003, 0, 0.007]}>
                <mesh name="Object_4002" geometry={nodes.Object_4002.geometry} material={materials['hedge.002']} position={[-0.407, 0, 0]} />
                <mesh name="Object_5002" geometry={nodes.Object_5002.geometry} material={materials['TexturesCom_Branches0026_1_S.002']} position={[-0.407, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[-6.807, -0.06, 24.894]} rotation={[-Math.PI / 2, 0, 2.505]} scale={1.125}>
          <group name="f09a712ca05e4255af743803652e579afbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode002">
                <group name="Object_4003">
                  <primitive object={nodes._rootJoint} />
                  <group name="Character_Male_GreenJacket" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                </group>
                <group name="Object_4004">
                  <primitive object={nodes._rootJoint_1} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model006" rotation={[-Math.PI, 0, 0]} scale={102.992}>
          <group name="paper_and_tabletfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode003">
              <group name="Plane_1" scale={100} />
              <group name="Plane005_1" position={[-0.084, 11.203, 0.136]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model007" position={[0, 2.21, 25.181]} scale={-0.052}>
          <group name="LetterFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode004">
              <group name="Letter" position={[0, 0, -0.052]} rotation={[Math.PI, 0, Math.PI]} scale={[1, 1, 0.791]} />
            </group>
          </group>
        </group>
        <group name="Empty" position={[7.991, -0.082, -38.245]} scale={[17.662, 15.745, 16.806]} />
        <group name="Empty003" position={[7.991, -0.082, -38.245]} scale={[17.662, 15.745, 16.806]} />
        <group name="LINE" position={[44.031, -0.082, 1.392]} scale={[1.051, 0.937, 1]} />
        <mesh name="EntranceSideEast" geometry={nodes.EntranceSideEast.geometry} material={nodes.EntranceSideEast.material} position={[-6.425, -0.082, -4.181]} scale={[1.051, 0.937, 1]} />
        <mesh name="EntranceSideWest" geometry={nodes.EntranceSideWest.geometry} material={nodes.EntranceSideWest.material} position={[-8.401, -0.082, -4.181]} scale={[1.051, 0.937, 1]} />
        <mesh name="GFE0" geometry={nodes.GFE0.geometry} material={nodes.GFE0.material} position={[-4.323, -0.082, -1.898]} scale={[1.051, 0.937, 1]} />
        <mesh name="GFE1" geometry={nodes.GFE1.geometry} material={nodes.GFE1.material} position={[-4.298, -0.082, -6.707]} scale={[1.051, 0.937, 1]} />
        <mesh name="GFE2" geometry={nodes.GFE2.geometry} material={nodes.GFE2.material} position={[-4.298, -0.082, -11.563]} scale={[1.051, 0.937, 1]} />
        <mesh name="GFE3" geometry={nodes.GFE3.geometry} material={nodes.GFE3.material} position={[-4.298, -0.082, -16.363]} scale={[1.051, 0.937, 1]} />
        <mesh name="GFW0" geometry={nodes.GFW0.geometry} material={nodes.GFW0.material} position={[-17.852, -0.082, -1.873]} scale={[1.051, 0.937, 1]} />
        <mesh name="GFW1" geometry={nodes.GFW1.geometry} material={nodes.GFW1.material} position={[-17.852, -0.082, -6.637]} scale={[1.051, 0.937, 1]} />
        <mesh name="GFW2" geometry={nodes.GFW2.geometry} material={nodes.GFW2.material} position={[-17.852, -0.082, -11.599]} scale={[1.051, 0.937, 1]} />
        <mesh name="GFW3" geometry={nodes.GFW3.geometry} material={nodes.GFW3.material} position={[-17.852, -0.082, -16.335]} scale={[1.051, 0.937, 1]} />
        <mesh name="port0End" geometry={nodes.port0End.geometry} material={materials.cabinBottomRight} position={[-0.643, 1.603, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides" geometry={nodes.port0Sides.geometry} material={materials['Material.006']} position={[-0.643, 1.603, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides" geometry={nodes.port1Sides.geometry} material={materials['Material.013']} position={[-0.643, 1.603, -4.667]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides001" geometry={nodes.port1Sides001.geometry} material={materials['Material.013']} position={[-0.643, 1.603, -9.788]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides001" geometry={nodes.port0Sides001.geometry} material={materials['Material.014']} position={[-0.643, 1.603, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End001" geometry={nodes.port0End001.geometry} material={materials.whiteCabin} position={[-0.643, 1.603, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides002" geometry={nodes.port1Sides002.geometry} material={materials['Material.009']} position={[-0.643, 1.603, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End002" geometry={nodes.port1End002.geometry} material={materials.greyCabinPlain} position={[-0.643, 1.603, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides002" geometry={nodes.port0Sides002.geometry} material={materials.cabinTopRight} position={[-0.643, 1.603, -12.349]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides003" geometry={nodes.port1Sides003.geometry} material={materials['Material.008']} position={[-0.643, 4.972, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides004" geometry={nodes.port1Sides004.geometry} material={materials['Sides.007']} position={[-0.643, 4.972, -9.788]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides005" geometry={nodes.port1Sides005.geometry} material={materials['Sides.008']} position={[-0.643, 4.972, -4.667]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End003" geometry={nodes.port1End003.geometry} material={materials.CABINLSHAPEYELLOW} position={[-0.643, 4.972, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End004" geometry={nodes.port1End004.geometry} material={materials.whiteCabin} position={[-0.643, 4.972, -9.788]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides003" geometry={nodes.port0Sides003.geometry} material={materials['Sides.009']} position={[-0.643, 4.972, -12.349]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides004" geometry={nodes.port0Sides004.geometry} material={materials['Sides.010']} position={[-0.643, 4.972, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides005" geometry={nodes.port0Sides005.geometry} material={materials['Material.005']} position={[-0.643, 4.972, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End005" geometry={nodes.port0End005.geometry} material={materials.greyCabinPlain} position={[-5.485, 4.972, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides006" geometry={nodes.port1Sides006.geometry} material={materials['Material.014']} position={[-0.643, 8.341, -4.667]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides007" geometry={nodes.port1Sides007.geometry} material={materials['Sides.013']} position={[-0.643, 8.341, -9.788]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides008" geometry={nodes.port1Sides008.geometry} material={materials['Material.007']} position={[-0.643, 8.341, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End008" geometry={nodes.port1End008.geometry} material={materials.greyCabinPlain} position={[-0.643, 8.341, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides006" geometry={nodes.port0Sides006.geometry} material={materials['Material.004']} position={[-0.643, 8.341, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides007" geometry={nodes.port0Sides007.geometry} material={materials['Sides.016']} position={[-0.643, 8.341, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides008" geometry={nodes.port0Sides008.geometry} material={materials['Sides.017']} position={[-0.643, 8.341, -12.349]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End006" geometry={nodes.port0End006.geometry} material={materials.cabinTopRight} position={[-0.643, 8.341, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End007" geometry={nodes.port0End007.geometry} material={materials.whiteCabin} position={[-0.643, 8.341, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides009" geometry={nodes.port1Sides009.geometry} material={materials['Material.010']} position={[-19.854, 8.341, -13.626]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides010" geometry={nodes.port1Sides010.geometry} material={materials['Sides.019']} position={[-15.012, 8.341, -9.788]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides011" geometry={nodes.port1Sides011.geometry} material={materials['Sides.020']} position={[-15.012, 8.341, -4.667]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides012" geometry={nodes.port1Sides012.geometry} material={materials['Sides.021']} position={[-15.012, 4.972, -4.667]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides013" geometry={nodes.port1Sides013.geometry} material={materials['Sides.022']} position={[-15.012, 4.972, -9.788]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides014" geometry={nodes.port1Sides014.geometry} material={materials['Material.011']} position={[-15.012, 4.972, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides015" geometry={nodes.port1Sides015.geometry} material={materials['Material.012']} position={[-15.012, 1.603, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides016" geometry={nodes.port1Sides016.geometry} material={materials.cabinBottomRight} position={[-15.012, 1.603, -9.788]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1Sides017" geometry={nodes.port1Sides017.geometry} material={materials.cabinTopRight} position={[-15.012, 1.603, -4.667]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End009" geometry={nodes.port1End009.geometry} material={materials.cabinTopRight} position={[-15.012, 8.341, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End013" geometry={nodes.port1End013.geometry} material={materials.whiteCabin} position={[-15.012, 4.972, -9.788]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End014" geometry={nodes.port1End014.geometry} material={materials.greyCabinPlain} position={[-15.012, 4.972, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End015" geometry={nodes.port1End015.geometry} material={materials.cabinBottomRight} position={[-15.012, 1.603, -14.907]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End016" geometry={nodes.port1End016.geometry} material={materials.blueGlass} position={[-15.01, 1.603, -9.788]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End017" geometry={nodes.port1End017.geometry} material={materials.blueGlass} position={[-15.01, 1.603, -4.667]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides009" geometry={nodes.port0Sides009.geometry} material={materials['Sides.027']} position={[-15.012, 8.341, -12.349]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides010" geometry={nodes.port0Sides010.geometry} material={materials['Sides.028']} position={[-15.012, 8.341, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides011" geometry={nodes.port0Sides011.geometry} material={materials['Material.001']} position={[-15.012, 8.341, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides012" geometry={nodes.port0Sides012.geometry} material={materials['Material.002']} position={[-15.012, 4.972, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides013" geometry={nodes.port0Sides013.geometry} material={materials['Sides.031']} position={[-15.012, 4.972, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides014" geometry={nodes.port0Sides014.geometry} material={materials['Sides.032']} position={[-15.012, 4.972, -12.349]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides015" geometry={nodes.port0Sides015.geometry} material={materials.cabinBottomRight} position={[-15.012, 1.603, -12.349]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides016" geometry={nodes.port0Sides016.geometry} material={materials.cabinTopRight} position={[-15.012, 1.603, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0Sides017" geometry={nodes.port0Sides017.geometry} material={materials['Material.003']} position={[-15.012, 1.603, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End010" geometry={nodes.port0End010.geometry} material={materials.whiteCabin} position={[-15.012, 8.341, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End011" geometry={nodes.port0End011.geometry} material={materials.greyCabinPlain} position={[-10.17, 8.341, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End012" geometry={nodes.port0End012.geometry} material={materials.CABINLSHAPEYELLOW} position={[-15.012, 4.972, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End015" geometry={nodes.port0End015.geometry} material={materials.blueGlass} position={[-15.01, 1.603, -12.349]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End016" geometry={nodes.port0End016.geometry} material={materials.whiteCabin} position={[-15.012, 1.603, -7.23]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End017" geometry={nodes.port0End017.geometry} material={materials.cabinBottomRight} position={[-15.012, 1.603, -2.109]} rotation={[0, 1.571, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="frontYellow" geometry={nodes.frontYellow.geometry} material={materials['Material.014']} position={[-6.476, 6.535, -1.761]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.013, 0.013, 0.023]} />
        <mesh name="frontYellow001" geometry={nodes.frontYellow001.geometry} material={materials['Material.013']} position={[-7.824, 5.754, -14.9]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.013, 0.013, 0.021]} />
        <mesh name="portPanelRight" geometry={nodes.portPanelRight.geometry} material={materials.yellowCabinDoor} position={[-20.611, 8.34, -15.666]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft" geometry={nodes.portPanelLeft.geometry} material={materials.yellowCabinDoor} position={[-20.611, 8.34, -18.217]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight001" geometry={nodes.portPanelRight001.geometry} material={materials.yellowCabinDoor} position={[-20.611, 8.34, -13.061]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft001" geometry={nodes.portPanelLeft001.geometry} material={materials.yellowCabinDoor} position={[-20.611, 8.34, -15.612]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight002" geometry={nodes.portPanelRight002.geometry} material={materials.whitePortacabinDoor} position={[-20.611, 8.34, -7.985]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft002" geometry={nodes.portPanelLeft002.geometry} material={materials.whitePortacabinDoor} position={[-20.611, 8.34, -10.536]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight003" geometry={nodes.portPanelRight003.geometry} material={materials.yellowCabinDoor} position={[-20.611, 4.763, -7.985]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft003" geometry={nodes.portPanelLeft003.geometry} material={materials.yellowCabinDoor} position={[-20.611, 4.763, -10.536]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight004" geometry={nodes.portPanelRight004.geometry} material={materials['Front.047']} position={[-20.611, 4.763, -10.568]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft004" geometry={nodes.portPanelLeft004.geometry} material={materials.yellowCabinDoor} position={[-20.611, 4.763, -13.119]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight005" geometry={nodes.portPanelRight005.geometry} material={materials.yellowCabinDoor} position={[-20.611, 4.763, -15.662]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft005" geometry={nodes.portPanelLeft005.geometry} material={materials.yellowCabinDoor} position={[-20.611, 4.763, -18.214]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight006" geometry={nodes.portPanelRight006.geometry} material={materials.yellowCabinDoor} position={[4.948, 4.763, -1.273]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight007" geometry={nodes.portPanelRight007.geometry} material={materials.yellowCabinDoor} position={[4.95, 4.763, -3.856]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight008" geometry={nodes.portPanelRight008.geometry} material={materials.yellowCabinDoor} position={[4.951, 4.763, -8.951]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight009" geometry={nodes.portPanelRight009.geometry} material={materials.yellowCabinDoor} position={[4.951, 8.34, -8.951]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight010" geometry={nodes.portPanelRight010.geometry} material={materials.yellowCabinDoor} position={[4.949, 8.34, -6.333]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelRight011" geometry={nodes.portPanelRight011.geometry} material={materials.yellowCabinDoor} position={[4.948, 8.34, -1.269]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft006" geometry={nodes.portPanelLeft006.geometry} material={materials.whitePortacabinDoor} position={[4.947, 4.763, 1.279]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft007" geometry={nodes.portPanelLeft007.geometry} material={materials.whitePortacabinDoor} position={[4.949, 4.763, -1.305]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft008" geometry={nodes.portPanelLeft008.geometry} material={materials.whitePortacabinDoor} position={[4.95, 4.763, -6.399]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft009" geometry={nodes.portPanelLeft009.geometry} material={materials.whitePortacabinDoor} position={[4.95, 8.34, -6.399]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft010" geometry={nodes.portPanelLeft010.geometry} material={materials.whitePortacabinDoor} position={[4.948, 8.34, -3.781]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="portPanelLeft011" geometry={nodes.portPanelLeft011.geometry} material={materials.whitePortacabinDoor} position={[4.947, 8.34, 1.282]} rotation={[0, 0.017, 0]} scale={[0.007, 0.017, 0.016]} />
        <mesh name="port1End010" geometry={nodes.port1End010.geometry} material={materials.blueGlass} position={[-0.65, 1.603, -12.27]} rotation={[0, -1.57, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port1End011" geometry={nodes.port1End011.geometry} material={materials.blueGlass} position={[-0.652, 1.603, -9.689]} rotation={[0, -1.57, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="port0End009" geometry={nodes.port0End009.geometry} material={materials.blueGlass} position={[-0.653, 1.603, -4.588]} rotation={[0, -1.57, 0]} scale={[0.013, 0.017, 0.017]} />
        <mesh name="roofFrontBeamLeft" geometry={nodes.roofFrontBeamLeft.geometry} material={nodes.roofFrontBeamLeft.material} position={[-15.06, 10.173, -0.933]} scale={[4.946, 0.148, 0.118]} />
        <mesh name="roofFrontBeamRight" geometry={nodes.roofFrontBeamRight.geometry} material={nodes.roofFrontBeamRight.material} position={[-0.628, 10.173, -0.933]} scale={[4.946, 0.148, 0.118]} />
        <mesh name="EntranceSignLarge" geometry={nodes.EntranceSignLarge.geometry} material={nodes.EntranceSignLarge.material} position={[-8.674, 2.281, -0.469]} scale={[0.317, 0.41, 0.01]} />
        <mesh name="EntranceSignSmall001" geometry={nodes.EntranceSignSmall001.geometry} material={nodes.EntranceSignSmall001.material} position={[-8.65, 1.588, -0.475]} scale={[0.095, 0.164, 0.003]} />
        <mesh name="circleLightLeft001" geometry={nodes.circleLightLeft001.geometry} material={materials.circleLightBlack} position={[-11.106, 3.136, -0.826]} rotation={[Math.PI / 2, 0, 0]} scale={0.168} />
        <mesh name="alarm" geometry={nodes.alarm.geometry} material={materials.blue_glass_01} position={[-8.681, 3.882, -0.454]} scale={0.017} />
        <mesh name="alarmTop" geometry={nodes.alarmTop.geometry} material={materials.alarmTexture} position={[-8.681, 3.882, -0.454]} scale={0.017} />
        <mesh name="roofLeft" geometry={nodes.roofLeft.geometry} material={nodes.roofLeft.material} position={[-14.592, 10.13, -8.64]} scale={[5.414, 0.094, 7.588]} />
        <mesh name="roofRight" geometry={nodes.roofRight.geometry} material={nodes.roofRight.material} position={[-1.054, 10.13, -8.64]} scale={[5.419, 0.094, 7.588]} />
        <mesh name="roofRight001" geometry={nodes.roofRight001.geometry} material={nodes.roofRight001.material} position={[-7.823, 10.13, -8.323]} scale={[1.335, 0.094, 5.294]} />
        <mesh name="SindleDoor_Material_0" geometry={nodes.SindleDoor_Material_0.geometry} material={materials.frameYellow} position={[-0.034, 0.007, -0.011]} rotation={[Math.PI / 2, 0, 1.573]} scale={[1, 1.065, 1.266]} />
        <mesh name="window02001" geometry={nodes.window02001.geometry} material={materials.blueGlass} position={[-6.631, 3.643, -0.547]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.007, 0.008, 0.008]} />
        <mesh name="window01001" geometry={nodes.window01001.geometry} material={materials['Frame_out.001']} position={[-6.631, 3.643, -0.547]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.007, 0.008, 0.008]} />
        <mesh name="window0001" geometry={nodes.window0001.geometry} material={materials.frameYellow} position={[-6.631, 3.643, -0.547]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.007, 0.008, 0.008]} />
        <mesh name="window02002" geometry={nodes.window02002.geometry} material={materials.blueGlass} position={[-6.619, 1.343, -0.547]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.009, 0.008, 0.002]} />
        <mesh name="window01002" geometry={nodes.window01002.geometry} material={materials['Frame_out.002']} position={[-6.631, 1.343, -0.547]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.009, 0.008, 0.002]} />
        <mesh name="window0002" geometry={nodes.window0002.geometry} material={materials.frameYellow} position={[-6.629, 1.343, -0.547]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.009, 0.008, 0.002]} />
        <group name="window0003" position={[-6.631, 5.643, -0.547]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.006, 0.008, 0.008]}>
          <mesh name="Object_0004" geometry={nodes.Object_0004.geometry} material={materials.frameYellow} />
          <mesh name="Object_0004_1" geometry={nodes.Object_0004_1.geometry} material={materials.blueGlass} />
          <mesh name="Object_0004_2" geometry={nodes.Object_0004_2.geometry} material={materials['Frame_out.003']} />
        </group>
        <mesh name="windowDoor002" geometry={nodes.windowDoor002.geometry} material={materials.blueGlass} position={[-7.212, 1.334, -0.479]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 0.008, 0.005]} />
        <mesh name="windowDoor" geometry={nodes.windowDoor.geometry} material={materials['Frame_in.004']} position={[-7.212, 1.324, -0.547]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 0.007, 0.005]} />
        <mesh name="entranceWindowSidePanel0" geometry={nodes.entranceWindowSidePanel0.geometry} material={materials.blueGlass} position={[-9.135, 5.367, -2.046]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.035, 0.005, 0.005]} />
        <mesh name="entranceWindowSidePanel1" geometry={nodes.entranceWindowSidePanel1.geometry} material={materials.blueGlass} position={[-6.476, 6.535, -1.761]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.035, 0.005, 0.005]} />
        <group name="WINDOW" position={[-19.854, 8.488, -13.624]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0006" geometry={nodes.Object_0006.geometry} material={materials['Frame_in.005']} />
          <mesh name="Object_0006_1" geometry={nodes.Object_0006_1.geometry} material={materials['Glass.007']} />
          <mesh name="Object_0006_2" geometry={nodes.Object_0006_2.geometry} material={materials['Frame_out.005']} />
        </group>
        <group name="WINDOW001" position={[-19.854, 5.114, -13.624]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0007" geometry={nodes.Object_0007.geometry} material={materials['Frame_in.006']} />
          <mesh name="Object_0007_1" geometry={nodes.Object_0007_1.geometry} material={materials['Glass.008']} />
          <mesh name="Object_0007_2" geometry={nodes.Object_0007_2.geometry} material={materials['Frame_out.006']} />
        </group>
        <group name="WINDOW002" position={[-19.854, 5.114, -8.475]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0008" geometry={nodes.Object_0008.geometry} material={materials['Frame_in.007']} />
          <mesh name="Object_0008_1" geometry={nodes.Object_0008_1.geometry} material={materials['Glass.009']} />
          <mesh name="Object_0008_2" geometry={nodes.Object_0008_2.geometry} material={materials['Frame_out.007']} />
        </group>
        <group name="WINDOW003" position={[-19.854, 5.114, -5.923]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0009" geometry={nodes.Object_0009.geometry} material={materials['Frame_in.008']} />
          <mesh name="Object_0009_1" geometry={nodes.Object_0009_1.geometry} material={materials['Glass.010']} />
          <mesh name="Object_0009_2" geometry={nodes.Object_0009_2.geometry} material={materials['Frame_out.008']} />
        </group>
        <group name="WINDOW004" position={[-19.854, 8.454, -11.038]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0010" geometry={nodes.Object_0010.geometry} material={materials['Frame_in.009']} />
          <mesh name="Object_0010_1" geometry={nodes.Object_0010_1.geometry} material={materials['Glass.011']} />
          <mesh name="Object_0010_2" geometry={nodes.Object_0010_2.geometry} material={materials['Frame_out.009']} />
        </group>
        <group name="WINDOW005" position={[-19.854, 8.454, -5.923]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0011" geometry={nodes.Object_0011.geometry} material={materials['Frame_in.010']} />
          <mesh name="Object_0011_1" geometry={nodes.Object_0011_1.geometry} material={materials['Glass.012']} />
          <mesh name="Object_0011_2" geometry={nodes.Object_0011_2.geometry} material={materials['Frame_out.010']} />
        </group>
        <group name="WINDOW006" position={[4.137, 8.488, -13.624]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0012" geometry={nodes.Object_0012.geometry} material={materials['Frame_in.011']} />
          <mesh name="Object_0012_1" geometry={nodes.Object_0012_1.geometry} material={materials['Glass.013']} />
          <mesh name="Object_0012_2" geometry={nodes.Object_0012_2.geometry} material={materials['Frame_out.011']} />
        </group>
        <group name="WINDOW007" position={[4.163, 5.114, -13.624]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0013" geometry={nodes.Object_0013.geometry} material={materials['Frame_in.012']} />
          <mesh name="Object_0013_1" geometry={nodes.Object_0013_1.geometry} material={materials['Glass.014']} />
          <mesh name="Object_0013_2" geometry={nodes.Object_0013_2.geometry} material={materials['Frame_out.012']} />
        </group>
        <group name="WINDOW008" position={[4.153, 8.454, -11.038]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0014" geometry={nodes.Object_0014.geometry} material={materials['Frame_in.013']} />
          <mesh name="Object_0014_1" geometry={nodes.Object_0014_1.geometry} material={materials['Glass.015']} />
          <mesh name="Object_0014_2" geometry={nodes.Object_0014_2.geometry} material={materials['Frame_out.013']} />
        </group>
        <group name="WINDOW009" position={[4.002, 8.454, -5.923]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0015" geometry={nodes.Object_0015.geometry} material={materials['Frame_in.014']} />
          <mesh name="Object_0015_1" geometry={nodes.Object_0015_1.geometry} material={materials['Glass.016']} />
          <mesh name="Object_0015_2" geometry={nodes.Object_0015_2.geometry} material={materials['Frame_out.014']} />
        </group>
        <group name="WINDOW010" position={[4.002, 5.114, -5.923]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0016" geometry={nodes.Object_0016.geometry} material={materials['Material.004']} />
          <mesh name="Object_0016_1" geometry={nodes.Object_0016_1.geometry} material={materials['Glass.017']} />
          <mesh name="Object_0016_2" geometry={nodes.Object_0016_2.geometry} material={materials['Frame_out.015']} />
        </group>
        <group name="WINDOW011" position={[4.002, 5.114, -8.475]} rotation={[0, 0, Math.PI / 2]} scale={[0.011, 0.008, 0.013]}>
          <mesh name="Object_0017" geometry={nodes.Object_0017.geometry} material={materials['Frame_in.016']} />
          <mesh name="Object_0017_1" geometry={nodes.Object_0017_1.geometry} material={materials['Glass.018']} />
          <mesh name="Object_0017_2" geometry={nodes.Object_0017_2.geometry} material={materials['Frame_out.016']} />
        </group>
        <mesh name="circleLightLeft002" geometry={nodes.circleLightLeft002.geometry} material={materials['circleLightBlack.001']} position={[-4.439, 3.136, -0.826]} rotation={[Math.PI / 2, 0, 0]} scale={0.168} />
        <mesh name="ground" geometry={nodes.ground.geometry} material={materials['Material.017']} position={[-7.762, -1.081, 51.543]} scale={[18.532, 1, 51.308]} />
        <mesh name="pavement" geometry={nodes.pavement.geometry} material={materials.Material} position={[-7.762, -0.055, 0.247]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-13.833, -0.012, -1.069]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.016']} position={[-19.854, 2.196, -1.667]} rotation={[Math.PI, -0.844, Math.PI]} scale={45.426} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[52.34, -0.082, 0]} scale={[1.051, 0.937, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
